// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubsidyTracker.Data;

#nullable disable

namespace SubsidyTracker.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219012409_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("SubsidyTracker.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "LIVING",
                            Description = "생활안정 지원금",
                            Name = "생활안정"
                        },
                        new
                        {
                            Id = 2,
                            Code = "HOUSING",
                            Description = "주거 및 자립 지원",
                            Name = "주거·자립"
                        },
                        new
                        {
                            Id = 3,
                            Code = "EDUCATION",
                            Description = "보육 및 교육 지원",
                            Name = "보육·교육"
                        },
                        new
                        {
                            Id = 4,
                            Code = "EMPLOYMENT",
                            Description = "고용 및 창업 지원",
                            Name = "고용·창업"
                        },
                        new
                        {
                            Id = 5,
                            Code = "HEALTH",
                            Description = "보건 및 의료 지원",
                            Name = "보건·의료"
                        },
                        new
                        {
                            Id = 6,
                            Code = "ADMIN",
                            Description = "행정 및 안전 지원",
                            Name = "행정·안전"
                        },
                        new
                        {
                            Id = 7,
                            Code = "CULTURE",
                            Description = "문화 및 환경 지원",
                            Name = "문화·환경"
                        },
                        new
                        {
                            Id = 8,
                            Code = "AGRICULTURE",
                            Description = "농림 및 축산 지원",
                            Name = "농림·축산"
                        },
                        new
                        {
                            Id = 9,
                            Code = "ETC",
                            Description = "기타 지원",
                            Name = "기타"
                        },
                        new
                        {
                            Id = 10,
                            Code = "YOUTH",
                            Description = "청년 정책 및 지원",
                            Name = "청년"
                        });
                });

            modelBuilder.Entity("SubsidyTracker.Core.Models.CollectionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("ItemsCollected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CollectionLogs");
                });

            modelBuilder.Entity("SubsidyTracker.Core.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ALL",
                            Name = "전국"
                        },
                        new
                        {
                            Id = 2,
                            Code = "SEOUL",
                            Name = "서울특별시"
                        },
                        new
                        {
                            Id = 3,
                            Code = "BUSAN",
                            Name = "부산광역시"
                        },
                        new
                        {
                            Id = 4,
                            Code = "DAEGU",
                            Name = "대구광역시"
                        },
                        new
                        {
                            Id = 5,
                            Code = "INCHEON",
                            Name = "인천광역시"
                        },
                        new
                        {
                            Id = 6,
                            Code = "GWANGJU",
                            Name = "광주광역시"
                        },
                        new
                        {
                            Id = 7,
                            Code = "DAEJEON",
                            Name = "대전광역시"
                        },
                        new
                        {
                            Id = 8,
                            Code = "ULSAN",
                            Name = "울산광역시"
                        },
                        new
                        {
                            Id = 9,
                            Code = "SEJONG",
                            Name = "세종특별자치시"
                        },
                        new
                        {
                            Id = 10,
                            Code = "GYEONGGI",
                            Name = "경기도"
                        },
                        new
                        {
                            Id = 11,
                            Code = "GANGWON",
                            Name = "강원특별자치도"
                        },
                        new
                        {
                            Id = 12,
                            Code = "CHUNGBUK",
                            Name = "충청북도"
                        },
                        new
                        {
                            Id = 13,
                            Code = "CHUNGNAM",
                            Name = "충청남도"
                        },
                        new
                        {
                            Id = 14,
                            Code = "JEONBUK",
                            Name = "전북특별자치도"
                        },
                        new
                        {
                            Id = 15,
                            Code = "JEONNAM",
                            Name = "전라남도"
                        },
                        new
                        {
                            Id = 16,
                            Code = "GYEONGBUK",
                            Name = "경상북도"
                        },
                        new
                        {
                            Id = 17,
                            Code = "GYEONGNAM",
                            Name = "경상남도"
                        },
                        new
                        {
                            Id = 18,
                            Code = "JEJU",
                            Name = "제주특별자치도"
                        });
                });

            modelBuilder.Entity("SubsidyTracker.Core.Models.Subsidy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Amount")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApplicationEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationMethod")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ApplicationStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EligibilityCriteria")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExternalId");

                    b.HasIndex("RegionId");

                    b.HasIndex("Status");

                    b.HasIndex("ViewCount");

                    b.ToTable("Subsidies");
                });

            modelBuilder.Entity("SubsidyTracker.Core.Models.SubsidyTargetGroup", b =>
                {
                    b.Property<int>("SubsidyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SubsidyId", "TargetGroupId");

                    b.HasIndex("TargetGroupId");

                    b.ToTable("SubsidyTargetGroups");
                });

            modelBuilder.Entity("SubsidyTracker.Core.Models.TargetGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TargetGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "YOUTH",
                            Name = "청년"
                        },
                        new
                        {
                            Id = 2,
                            Code = "MIDDLE",
                            Name = "중장년"
                        },
                        new
                        {
                            Id = 3,
                            Code = "SENIOR",
                            Name = "노인"
                        },
                        new
                        {
                            Id = 4,
                            Code = "DISABLED",
                            Name = "장애인"
                        },
                        new
                        {
                            Id = 5,
                            Code = "LOWINCOME",
                            Name = "저소득층"
                        },
                        new
                        {
                            Id = 6,
                            Code = "MULTICULTURAL",
                            Name = "다문화가정"
                        },
                        new
                        {
                            Id = 7,
                            Code = "SINGLEPARENT",
                            Name = "한부모가정"
                        },
                        new
                        {
                            Id = 8,
                            Code = "PREGNANT",
                            Name = "임산부"
                        },
                        new
                        {
                            Id = 9,
                            Code = "INFANT",
                            Name = "영유아"
                        },
                        new
                        {
                            Id = 10,
                            Code = "ALL",
                            Name = "전체"
                        });
                });

            modelBuilder.Entity("SubsidyTracker.Core.Models.Region", b =>
                {
                    b.HasOne("SubsidyTracker.Core.Models.Region", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SubsidyTracker.Core.Models.Subsidy", b =>
                {
                    b.HasOne("SubsidyTracker.Core.Models.Category", "Category")
                        .WithMany("Subsidies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SubsidyTracker.Core.Models.Region", "Region")
                        .WithMany("Subsidies")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("SubsidyTracker.Core.Models.SubsidyTargetGroup", b =>
                {
                    b.HasOne("SubsidyTracker.Core.Models.Subsidy", "Subsidy")
                        .WithMany("SubsidyTargetGroups")
                        .HasForeignKey("SubsidyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SubsidyTracker.Core.Models.TargetGroup", "TargetGroup")
                        .WithMany("SubsidyTargetGroups")
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subsidy");

                    b.Navigation("TargetGroup");
                });

            modelBuilder.Entity("SubsidyTracker.Core.Models.Category", b =>
                {
                    b.Navigation("Subsidies");
                });

            modelBuilder.Entity("SubsidyTracker.Core.Models.Region", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Subsidies");
                });

            modelBuilder.Entity("SubsidyTracker.Core.Models.Subsidy", b =>
                {
                    b.Navigation("SubsidyTargetGroups");
                });

            modelBuilder.Entity("SubsidyTracker.Core.Models.TargetGroup", b =>
                {
                    b.Navigation("SubsidyTargetGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
